version: 2
jobs:
  build:
    working_directory: /app
    # Docker image
    docker:
      # image: docker:17.05.0-ce-git
      - image: docker:stable-git
    steps:
      - checkout
      # Prevent docker-in-docker problem
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              make
      - run:
          name: Make docker image
          command: make
      - run:
          name: Run test
          command: |
            ls -la; \
            ignition=$(docker run --rm -it config-transpiler:latest ct -in-file ./.circleci/sample_cl-config.yml)
            control=$(cat ./.circleci/sample_cl-config.yml)
