version: 2
jobs:
  build:
    working_directory: /app
    # Docker image for docker in docker
    docker:
      # image: docker:17.05.0-ce-git
      - image: docker:stable-git
        environment:
          CIRCLE_TEST_REPORTS: /tmp/test-results
    steps:
      - checkout
      # Prevent docker-in-docker problem
      - setup_remote_docker
      - run:
          name: Display Server Env Info
          command: |
            docker version && \
            cat /etc/os-release
      - run:
          name: Makedir for test results
          command: mkdir -p ${CIRCLE_TEST_REPORTS}
      - run:
          name: Install dependencies
          command: apk add --no-cache make
      - run:
          name: Build docker image
          command: make
      - run:
          name: Run test
          command: |
            docker run --rm config-transpiler:latest /test/run_test.sh
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
