version: 2
jobs:
  build:
    working_directory: /app
    # Docker image for docker in docker
    docker:
      # image: docker:17.05.0-ce-git
      - image: docker:stable-git
    steps:
      - checkout
      # Prevent docker-in-docker problem
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: apk add --no-cache make
      - run:
          name: Build docker image
          command: make
      - run:
          name: Run test
          command: |
            docker run --rm config-transpiler:latest /test/run_test.sh
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - dockerfile:
          requires:
            - build
