version: 2
jobs:
  build:
    working_directory: /app
    # Build on docker image with git
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      # Prevent docker-in-docker problem
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              make
      - run:
          name: Make docker image
          command: make
      - run:
          name: Run test
          command: docker run --rm -it config-transpiler:0.0.1 ct -version
